package com.geoway.webstore.dao;

import com.geoway.webstore.entities.TbStudent;

public interface TbStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    int insert(TbStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    int insertSelective(TbStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    TbStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    int updateByPrimaryKeySelective(TbStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    int updateByPrimaryKey(TbStudent record);
}