server:
  port: 8001

spring:
  application:
    name: lencho-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://hadoop104:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456

    url: jdbc:postgresql://hadoop104:5432/db2021?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      #空闲连接是否被回收
      test-while-idle: true
      #申请连接时是否检测有效性
      test-on-borrow: false
      #归还连接时是否检测有效性
      test-on-return: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.geoway.webstore.entities

# 配置pagehelper参数
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

master:
  datasource:
    druid:
      driverClassName: org.gjt.mm.mysql.Driver
      #配置基本属性
      url: jdbc:mysql://hadoop104:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

second:
  datasource:
    druid:
      driverClassName: org.gjt.mm.mysql.Driver
      #配置基本属性
      url: jdbc:mysql://hadoop104:3306/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456