package com.geoway.webstore.entities;

public class TbStudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.id
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.name
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.age
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.no
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    private Integer no;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.id
     *
     * @return the value of tb_student.id
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.id
     *
     * @param id the value for tb_student.id
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.name
     *
     * @return the value of tb_student.name
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.name
     *
     * @param name the value for tb_student.name
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.age
     *
     * @return the value of tb_student.age
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.age
     *
     * @param age the value for tb_student.age
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.no
     *
     * @return the value of tb_student.no
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.no
     *
     * @param no the value for tb_student.no
     *
     * @mbg.generated Tue Sep 14 16:15:37 CST 2021
     */
    public void setNo(Integer no) {
        this.no = no;
    }
}